# Generated by Django 4.1 on 2023-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanmForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('aadhaar_number', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.CharField(max_length=100, null=True)),
                ('date_of_birth_in_words', models.CharField(max_length=100, null=True)),
                ('place_of_birth', models.CharField(max_length=100, null=True)),
                ('place_of_birth_local', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('father_aadhaar_number', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('mother_aadhaar_number', models.CharField(max_length=100, null=True)),
                ('permanent_address', models.CharField(max_length=100, null=True)),
                ('birth_address', models.CharField(max_length=100, null=True)),
                ('local_language', models.CharField(max_length=100, null=True)),
                ('date_of_registration', models.CharField(max_length=100, null=True)),
                ('date_of_issue', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('hospital_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
