# Generated by Django 3.2 on 2023-06-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_aadhaarform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AadhaarForm',
            new_name='Aadhaar',
        ),
    ]
