# Generated by Django 3.2 on 2023-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_aadhaarform_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaar',
            name='date_of_birth',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aadhaar',
            name='download_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaar',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaar',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='aadhaar',
            name='issue_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaar',
            name='local_language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Telugu', 'Telugu')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='aadhaar',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Husband', 'Husband')], default='Father', max_length=50),
        ),
    ]
