# Generated by Django 3.2 on 2023-06-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20230629_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JanmForm',
            new_name='Janm',
        ),
    ]
