# Generated by Django 3.2 on 2023-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_janmform_janm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janm',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='janm',
            name='local_language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Telugu', 'Telugu')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='janm',
            name='state',
            field=models.CharField(choices=[('state1', 'State 1'), ('state2', 'State 2'), ('state3', 'State 3')], default='', max_length=100),
        ),
    ]
