# Generated by Django 3.2 on 2023-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20230629_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janm',
            name='state',
            field=models.CharField(choices=[('state1', 'State 1'), ('state2', 'State 2'), ('state3', 'State 3')], default='state1', max_length=100),
        ),
    ]
