# Generated by Django 3.2 on 2023-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_janm_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='janm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
