# Generated by Django 3.2 on 2023-07-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20230709_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaar',
            name='qr',
        ),
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.ImageField(null=True, upload_to='qr')),
                ('adhaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.aadhaar')),
            ],
        ),
    ]
