# Generated by Django 3.2 on 2023-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20230709_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaar',
            name='gender',
            field=models.CharField(choices=[('Purush', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='janm',
            name='gender',
            field=models.CharField(choices=[('Purush', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50),
        ),
    ]
