# Generated by Django 3.2 on 2023-07-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20230711_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaar',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='janm',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50),
        ),
    ]
