# Generated by Django 3.2 on 2023-07-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20230711_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='janm',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.customuser'),
        ),
    ]
