# Generated by Django 3.2 on 2023-07-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_janm_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='janm',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='aadhaar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.customuser'),
        ),
    ]
