# Generated by Django 4.2.5 on 2024-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_aadhaar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='pancard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(max_length=100, null=True)),
                ('response', models.BooleanField(default=True)),
                ('details', models.TextField()),
            ],
        ),
    ]
