# Generated by Django 4.2.5 on 2024-04-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_pancard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pancard',
            new_name='pan_card',
        ),
    ]
